# Generated by Django 4.2.4 on 2023-09-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
