# Generated by Django 4.2.4 on 2023-09-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_alter_comment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussionpost",
            name="file_upload",
            field=models.FileField(default=None, upload_to="uploads/"),
        ),
    ]
