# Generated by Django 4.2.4 on 2023-09-28 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_alter_comment_discussion_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Lesson",
        ),
    ]
