# Generated by Django 4.2.4 on 2023-10-01 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0008_studentquiz"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentQuiz",
        ),
    ]
