# Generated by Django 4.2.4 on 2023-09-27 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("question1", models.CharField(max_length=255)),
                ("option1_1", models.CharField(max_length=100)),
                ("option1_2", models.CharField(max_length=100)),
                ("option1_3", models.CharField(max_length=100)),
                ("option1_4", models.CharField(max_length=100)),
                ("correct_answer1", models.IntegerField()),
                ("question2", models.CharField(max_length=255)),
                ("option2_1", models.CharField(max_length=100)),
                ("option2_2", models.CharField(max_length=100)),
                ("option2_3", models.CharField(max_length=100)),
                ("option2_4", models.CharField(max_length=100)),
                ("correct_answer2", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teachers.quiz"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
