# Generated by Django 4.2.4 on 2023-09-27 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0003_quiz_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="correct_answer1",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="correct_answer2",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="option1_1",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="option1_2",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="option1_3",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="option1_4",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="option2_1",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="option2_2",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="option2_3",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="option2_4",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="question1",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="question2",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="slug",
        ),
        migrations.AddField(
            model_name="quiz",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("option1", models.CharField(max_length=100)),
                ("option2", models.CharField(max_length=100)),
                ("option3", models.CharField(max_length=100)),
                ("option4", models.CharField(max_length=100)),
                ("correct_answer", models.IntegerField()),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teachers.quiz"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(
                related_name="quiz_questions", to="teachers.quizquestion"
            ),
        ),
    ]
