# Generated by Django 4.2.4 on 2023-09-28 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0004_remove_quiz_correct_answer1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
