# Generated by Django 4.2.4 on 2023-10-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0009_remove_quizquestion_question_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="question_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
