# Generated by Django 4.2.4 on 2023-10-01 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0010_quizquestion_question_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizquestion",
            name="question_number",
        ),
    ]
