# Generated by Django 4.2.4 on 2023-10-10 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teachers", "0013_alter_classroom_id_registereduser"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="student",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrolled_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
