# Generated by Django 4.2.4 on 2023-10-11 00:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0014_classroom_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="student",
        ),
    ]
