# Generated by Django 4.2.4 on 2023-10-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0015_remove_classroom_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
