# Generated by Django 4.2.4 on 2023-10-12 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0017_alter_classroom_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teachers.classroom",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teachers.classroom",
            ),
        ),
    ]
