# Generated by Django 4.2.4 on 2023-10-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0018_lesson_classroom_quiz_classroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="attempts_remaining",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
