# Generated by Django 4.2.4 on 2023-10-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0019_quizquestion_attempts_remaining"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="attempts_taken",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
