# Generated by Django 4.2.4 on 2023-10-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0020_quizquestion_attempts_taken"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="selected_answer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
