# Generated by Django 4.2.4 on 2023-11-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0021_quizquestion_selected_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz_weight", models.FloatField(default=0.4)),
            ],
        ),
    ]
