# Generated by Django 4.2.4 on 2023-11-23 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0022_weight"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Weight",
        ),
    ]
