# Generated by Django 4.2.4 on 2023-11-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0023_delete_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
